set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

ENV := env_var_or_default("ENV", "lab")
ENV_TFVARS_PATH := "../../env/OVH/" + ENV + ".tfvars"
[private]
_workspace:
    @tofu workspace select {{ ENV }} || tofu workspace new {{ ENV }}

validate:
    @tofu init -backend=false
    @tofu validate

plan:
    @tofu init
    @just _workspace
    @tofu plan -var-file={{ ENV_TFVARS_PATH }}

deploy:
    @tofu init
    @just _workspace
    @tofu apply -auto-approve -var-file={{ ENV_TFVARS_PATH }}

destroy:
    @tofu init
    @just _workspace
    @OVH_APPLICATION_KEY="$(sed -n 's/^[[:space:]]*ovh_application_key[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' {{ ENV_TFVARS_PATH }})" \
      OVH_APPLICATION_SECRET="$(sed -n 's/^[[:space:]]*ovh_application_secret[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' {{ ENV_TFVARS_PATH }})" \
      OVH_CONSUMER_KEY="$(sed -n 's/^[[:space:]]*ovh_consumer_key[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' {{ ENV_TFVARS_PATH }})" \
      tofu destroy -auto-approve -var-file={{ ENV_TFVARS_PATH }}
