#!/usr/bin/env bash
set -euo pipefail
umask 077

usage() {
  echo "usage: $0 {init|check|status} {clusters|bastion} PROJECT {s3|local}" >&2
  echo "       $0 migrate {clusters|bastion} PROJECT {legacy-local|s3|local} {s3|local}" >&2
  exit 2
}

action=${1:-}
stack=${2:-}
project=${3:-}

case "$stack" in clusters|bastion) ;; *) usage ;; esac
case "$project" in ''|.|..|*[!A-Za-z0-9._-]*) usage ;; esac

repo=${OVH_BACKEND_REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}
root="$repo/providers/ovh/$stack"
project_dir="$repo/env/OVH/$project"
generated="$root/backend.generated.tf"
export TF_DATA_DIR="$repo/.local/tofu-data/ovh/$project/$stack"
marker="$TF_DATA_DIR/infra-backend"
migration_marker="$TF_DATA_DIR/infra-backend-migration"
legacy_marker="$repo/.local/backend-state/ovh/legacy-$stack.migrated"
desired=
restore_root=
restore_workspace=
cleanup() {
  if [[ -n "$restore_root" && -n "$restore_workspace" ]]; then
    tofu -chdir="$restore_root" workspace select "$restore_workspace" >/dev/null 2>&1 || true
  fi
  rm -f "${desired:-}"
}
trap cleanup EXIT

# One shared, non-secret backend file per project. The per-stack key/workspace
# prefix are injected below so clusters and bastion never share a state path.
backend_config() {
  printf '%s/backend.s3.tfbackend' "$project_dir"
}

backend_key() {
  case "$stack" in
    clusters) printf 'cluster.tfstate' ;;
    bastion) printf 'bastion.tfstate' ;;
  esac
}

backend_prefix() {
  case "$stack" in
    clusters) printf 'clusters' ;;
    bastion) printf 'bastions' ;;
  esac
}

require_s3_config() {
  local config
  config=$(backend_config)
  if [[ ! -f "$config" ]]; then
    echo "Missing OVH S3 backend config: $config" >&2
    echo "Copy env/OVH/example/backend.s3.tfbackend and edit its non-secret values." >&2
    return 1
  fi
}

render() {
  local backend=$1 output=$2
  case "$backend" in
    s3)
      require_s3_config
      cat >"$output" <<'EOF'
# Generated by scripts/ovh-backend.sh; do not edit or commit.
terraform {
  backend "s3" {}
}
EOF
      ;;
    local)
      cat >"$output" <<EOF
# Generated by scripts/ovh-backend.sh; do not edit or commit.
terraform {
  backend "local" {
    path          = "../../../.local/backend-state/ovh/$project/$stack/default.tfstate"
    workspace_dir = "../../../.local/backend-state/ovh/$project/$stack/workspaces"
  }
}
EOF
      ;;
    *) usage ;;
  esac
}

fingerprint() {
  local backend=$1 definition=$2
  if [[ "$backend" == s3 ]]; then
    { sha256sum <"$definition"; sha256sum <"$(backend_config)"; printf 'key=%s prefix=%s\n' "$(backend_key)" "$(backend_prefix)"; } | sha256sum | cut -d' ' -f1
  else
    sha256sum <"$definition" | cut -d' ' -f1
  fi
}

read_marker() {
  initialized_stack= initialized_project= initialized_backend= initialized_fingerprint=
  [[ -f "$marker" ]] || return 1
  while IFS='=' read -r key value; do
    case "$key" in
      stack) initialized_stack=$value ;;
      project) initialized_project=$value ;;
      backend) initialized_backend=$value ;;
      fingerprint) initialized_fingerprint=$value ;;
    esac
  done <"$marker"
}

write_marker() {
  local backend=$1 hash=$2 tmp
  mkdir -p "$(dirname "$marker")"
  tmp="$marker.tmp"
  printf 'stack=%s\nproject=%s\nbackend=%s\nfingerprint=%s\n' \
    "$stack" "$project" "$backend" "$hash" >"$tmp"
  chmod 0600 "$tmp"
  mv "$tmp" "$marker"
}

write_migration_marker() {
  local from=$1 to=$2 tmp
  mkdir -p "$(dirname "$migration_marker")"
  tmp="$migration_marker.tmp.$BASHPID"
  printf 'stack=%s\nproject=%s\nfrom=%s\nto=%s\n' "$stack" "$project" "$from" "$to" >"$tmp"
  chmod 0600 "$tmp"
  mv "$tmp" "$migration_marker"
}

refuse_incomplete_migration() {
  [[ ! -f "$migration_marker" ]] && return 0
  echo "Incomplete OVH backend migration recorded: $migration_marker" >&2
  echo "Refusing backend operations until source/destination state is verified; see docs/procedures/ovh-backend.md." >&2
  return 1
}

desired_definition() {
  local backend=$1
  desired=$(mktemp "$root/.backend.generated.XXXXXX")
  render "$backend" "$desired"
}

backend_args() {
  local backend=$1
  BACKEND_ARGS=()
  if [[ "$backend" == s3 ]]; then
    BACKEND_ARGS=(
      -backend-config="$(backend_config)"
      -backend-config="key=$(backend_key)"
      -backend-config="workspace_key_prefix=$(backend_prefix)"
    )
  fi
}

has_legacy_state() {
  [[ -f "$root/terraform.tfstate" ]] && return 0
  compgen -G "$root/terraform.tfstate.d/*/terraform.tfstate" >/dev/null
}

assert_ready() {
  local backend=$1 expected_hash
  desired_definition "$backend"
  expected_hash=$(fingerprint "$backend" "$desired")
  if [[ ! -f "$TF_DATA_DIR/terraform.tfstate" ]] || ! read_marker || [[ "$initialized_stack" != "$stack" || "$initialized_project" != "$project" || "$initialized_backend" != "$backend" ]]; then
    local recipe=backend-init
    [[ "$stack" == bastion ]] && recipe=bastion-backend-init
    echo "OVH $stack backend is not initialized for PROJECT=$project BACKEND=$backend." >&2
    echo "Run: PROJECT=$project BACKEND=$backend just ovh::$recipe" >&2
    return 1
  fi
  if [[ "$initialized_fingerprint" != "$expected_hash" ]] || ! cmp -s "$desired" "$generated"; then
    if [[ "$initialized_fingerprint" != "$expected_hash" ]]; then
      echo "OVH $stack backend configuration changed after initialization." >&2
      echo "Use the explicit backend-migrate recipe; refusing an unsafe backend switch." >&2
      return 1
    fi
    mv "$desired" "$generated"
    desired=
  fi
}

init_backend() {
  local backend=$1 hash
  desired_definition "$backend"
  hash=$(fingerprint "$backend" "$desired")

  if read_marker; then
    if [[ "$initialized_stack" != "$stack" || "$initialized_project" != "$project" || "$initialized_backend" != "$backend" || "$initialized_fingerprint" != "$hash" ]]; then
      echo "A different backend is already initialized; use backend-migrate with explicit FROM and TO." >&2
      return 1
    fi
  elif { has_legacy_state && [[ ! -f "$legacy_marker" ]]; } || [[ -f "$TF_DATA_DIR/terraform.tfstate" ]]; then
    echo "Existing unclassified/legacy backend state found in $root." >&2
    echo "Use backend-migrate FROM=legacy-local TO=$backend; refusing to initialize empty state." >&2
    return 1
  fi

  mv "$desired" "$generated"
  desired=
  backend_args "$backend"
  tofu -chdir="$root" init "${BACKEND_ARGS[@]}"
  write_marker "$backend" "$hash"
  echo "Initialized OVH $stack backend: PROJECT=$project BACKEND=$backend"
}

backup_states() {
  local from=$1 to=$2 original line workspace state_file stamp
  stamp=$(date -u +%Y%m%dT%H%M%SZ)
  backup="$repo/.local/backend-backups/$stamp-$project-$stack-${from}-to-${to}-$BASHPID"
  mkdir -p "$backup"
  chmod 0700 "$backup"

  [[ -f "$TF_DATA_DIR/terraform.tfstate" ]] && cp "$TF_DATA_DIR/terraform.tfstate" "$backup/backend-metadata.tfstate"
  [[ -f "$generated" ]] && cp "$generated" "$backup/backend.generated.tf"
  [[ -f "$marker" ]] && cp "$marker" "$backup/infra-backend"
  find "$backup" -type f -exec chmod 0600 {} +

  original=$(tofu -chdir="$root" workspace show)
  restore_root=$root
  restore_workspace=$original
  workspace_list="$backup/workspaces.txt"
  tofu -chdir="$root" workspace list >"$workspace_list"
  chmod 0600 "$workspace_list"
  while IFS= read -r line; do
    workspace=${line#\*}
    workspace=${workspace#"${workspace%%[![:space:]]*}"}
    workspace=${workspace%"${workspace##*[![:space:]]}"}
    [[ -n "$workspace" ]] || continue
    case "$workspace" in .|..|*[!A-Za-z0-9._-]*) echo "Unsafe workspace name: $workspace" >&2; return 1 ;; esac
    tofu -chdir="$root" workspace select "$workspace" >/dev/null
    state_file="$backup/$workspace.tfstate"
    state_error="$backup/.state-pull-error"
    if ! tofu -chdir="$root" state pull >"$state_file" 2>"$state_error"; then
      if [[ "$workspace" == default ]] && [[ $(<"$state_error") == *"No state file was found"* ]]; then
        rm -f "$state_file" "$state_error"
        continue
      fi
      echo "Failed to back up workspace '$workspace'; migration aborted." >&2
      return 1
    fi
    rm -f "$state_error"
    chmod 0600 "$state_file"
  done <"$workspace_list"
  tofu -chdir="$root" workspace select "$original" >/dev/null
  restore_root=
  restore_workspace=
  echo "State backup: $backup"
}

migrate_backend() {
  local from=$1 to=$2 hash legacy_tmp
  case "$from" in legacy-local|s3|local) ;; *) usage ;; esac
  case "$to" in s3|local) ;; *) usage ;; esac
  [[ "$from" != legacy-local || "$to" != legacy-local ]] || usage
  [[ "$from" != "$to" || "$from" == s3 ]] || {
    echo "FROM and TO are identical; no backend migration is needed." >&2
    return 1
  }

  if [[ "$from" == legacy-local ]]; then
    if read_marker; then
      echo "Backend is already classified as $initialized_backend; FROM=legacy-local is unsafe." >&2
      return 1
    fi
    has_legacy_state || { echo "No legacy local state found in $root." >&2; return 1; }
    [[ ! -f "$legacy_marker" ]] || { echo "Legacy local state was already migrated; use its classified backend as FROM." >&2; return 1; }
    write_migration_marker "$from" "$to"
    rm -f "$generated"
    tofu -chdir="$root" init
  else
    if ! read_marker || [[ "$initialized_stack" != "$stack" || "$initialized_project" != "$project" || "$initialized_backend" != "$from" ]]; then
      echo "Initialized backend does not match FROM=$from for PROJECT=$project stack=$stack." >&2
      return 1
    fi
    write_migration_marker "$from" "$to"
  fi

  backup_states "$from" "$to"
  desired_definition "$to"
  hash=$(fingerprint "$to" "$desired")
  mv "$desired" "$generated"
  desired=
  backend_args "$to"
  echo "Migrating $stack backend for PROJECT=$project: $from -> $to"
  echo "OpenTofu will ask whether to migrate all workspaces; answer yes only when"
  echo "the destination is empty or you intend to overwrite its state."
  tofu -chdir="$root" init -migrate-state "${BACKEND_ARGS[@]}"
  write_marker "$to" "$hash"
  if [[ "$from" == legacy-local ]]; then
    mkdir -p "$(dirname "$legacy_marker")"
    legacy_tmp="$legacy_marker.tmp.$BASHPID"
    printf 'project=%s\nbackend=%s\n' "$project" "$to" >"$legacy_tmp"
    chmod 0600 "$legacy_tmp"
    mv "$legacy_tmp" "$legacy_marker"
  fi
  rm -f "$migration_marker"
  echo "Migration complete. Keep the backup until plans for every workspace are verified."
}

refuse_incomplete_migration

case "$action" in
  init|check|status)
    backend=${4:-}
    case "$backend" in s3|local) ;; *) usage ;; esac
    case "$action" in
      init) init_backend "$backend" ;;
      check) assert_ready "$backend" ;;
      status)
        assert_ready "$backend"
        echo "OVH $stack backend initialized: PROJECT=$project BACKEND=$backend"
        ;;
    esac
    ;;
  migrate)
    [[ $# -eq 5 ]] || usage
    migrate_backend "$4" "$5"
    ;;
  *) usage ;;
esac
