###
### Generate the hosts.ini file
###

locals {
  vm_ipv4_addresses = {
    for vm_name, vm in local.all_vms_map :
    vm_name => try([
      for addr in libvirt_domain.vms[vm_name].network_interface[0].addresses :
      addr if can(regex("^\\d+\\.\\d+\\.\\d+\\.\\d+$", addr))
    ], [])
  }

  vm_operator_endpoints = {
    for vm_name, vm in local.all_vms_map :
    vm_name => coalesce(
      vm.ip,
      try(element(local.vm_ipv4_addresses[vm_name], 0), null),
      local.vm_fqdns[vm_name]
    )
  }

  ## Kubernetes API endpoint — first master's operator-accessible address
  kube_api_endpoint = local.first_master_name != null ? local.vm_operator_endpoints[local.first_master_name] : null
}

# IPv6 generated by some cloud images can break the inventory
resource "null_resource" "sleep_before_inventory" {
  count = local.write_local_artifacts ? 1 : 0

  provisioner "local-exec" {
    command = "sleep 60"
  }

  depends_on = [
    libvirt_domain.vms
  ]
}

resource "local_file" "ansible_inventory" {
  count = local.write_local_artifacts ? 1 : 0

  content = local.rendered_ansible_inventory

  filename = "${local.env_path}/hosts.ini"

  depends_on = [
    null_resource.env_directory,
    null_resource.sleep_before_inventory
  ]
}

###
### Output the rendered hosts.ini content in gitops mode, otherwise null
###
output "gitops_hosts_ini" {
  description = "GitOps-mode rendered inventory content."
  value       = local.gitops_mode ? local.rendered_ansible_inventory : null
}

###
### Import Kubeconfig
###

locals {
  kubeconfig_remote_path = (
    var.cluster.cloud_init_selected == "rke2" ? "/etc/rancher/rke2/rke2.yaml" : (
      var.cluster.cloud_init_selected == "k3s" ? "/etc/rancher/k3s/k3s.yaml" : null
    )
  )
}


# Output kubeconfig retrieval details in gitops mode, otherwise null
output "gitops_kubeconfig_host" {
  description = "GitOps-mode preferred endpoint for kubeconfig retrieval."
  value       = contains(["k3s", "rke2"], var.cluster.cloud_init_selected) && local.first_master_name != null ? local.vm_operator_endpoints[local.first_master_name] : null
}

output "gitops_kubeconfig_user" {
  description = "GitOps-mode SSH username for kubeconfig retrieval."
  value       = contains(["k3s", "rke2"], var.cluster.cloud_init_selected) ? var.cluster.username : null
}

output "gitops_kubeconfig_remote_path" {
  description = "GitOps-mode remote kubeconfig path on the first master."
  value       = local.kubeconfig_remote_path
}

###
### Output on terminal
###

# Output the node IPs
output "cluster_nodes" {
  description = "The preferred operator endpoints of the cluster nodes."

  value = {
    controller_ips = [
      for vm_name, vm in local.masters_map : local.vm_operator_endpoints[vm_name]
    ]

    worker_ips = [
      for vm_name, vm in local.workers_map : local.vm_operator_endpoints[vm_name]
    ]

    vm_ips = [
      for vm_name, vm in local.vms_map : local.vm_operator_endpoints[vm_name]
    ]

    masters = [
      for vm_name, vm in local.masters_map : local.vm_operator_endpoints[vm_name]
    ]

    workers = [
      for vm_name, vm in local.workers_map : local.vm_operator_endpoints[vm_name]
    ]

    public_ips = concat(
      [for vm_name, vm in local.masters_map : local.vm_operator_endpoints[vm_name]],
      [for vm_name, vm in local.workers_map : local.vm_operator_endpoints[vm_name]],
      [for vm_name, vm in local.vms_map : local.vm_operator_endpoints[vm_name]],
    )

    # Libvirt exposes one operator-reachable VM endpoint; for local NAT/bridge
    # deployments the private and operator endpoints are intentionally the same.
    private_ips = {
      controllers = [for vm_name, vm in local.masters_map : local.vm_operator_endpoints[vm_name]]
      workers     = [for vm_name, vm in local.workers_map : local.vm_operator_endpoints[vm_name]]
      vms         = [for vm_name, vm in local.vms_map : local.vm_operator_endpoints[vm_name]]
      all         = [for vm_name, vm in local.all_vms_map : local.vm_operator_endpoints[vm_name]]
    }


    ssh_first_master = local.write_local_artifacts && local.first_master_name != null ? "ssh -o StrictHostKeyChecking=no -i env/${var.infra_provider}/${terraform.workspace}/.key.private ${var.cluster.username}@${local.vm_operator_endpoints[local.first_master_name]}" : null
  }
}

output "kubeconfig_command" {
  value = local.write_local_artifacts && local.k8s_master_user_data_enabled && local.first_master_name != null ? (<<-EOT
kubecm add -cf env/${var.infra_provider}/${terraform.workspace}/kubeconfig --context-name ${var.cluster.cloud_init_selected}-${var.infra_provider}-${terraform.workspace} --create
# Or :
export KUBECONFIG=env/${var.infra_provider}/${terraform.workspace}/kubeconfig
# Then :
kubectl get nodes
EOT
  ) : ""
}
