###
### Generate the hosts.ini file
###

# IPv6 generated by some cloud images can break the inventory
resource "null_resource" "sleep_before_inventory" {

  provisioner "local-exec" {
    command = "sleep 60"
  }

  depends_on = [
    libvirt_domain.masters,
    libvirt_domain.workers
  ]
}

resource "local_file" "ansible_inventory" {

  content = templatefile("../shared/inventory/hosts.tpl", {

    controller_ips = flatten([
      for m in libvirt_domain.masters :
      [
        for addr in m.network_interface[0].addresses :
        addr if can(regex("^\\d+\\.\\d+\\.\\d+\\.\\d+$", addr))
      ]
    ])

    worker_ips = flatten([
      for w in libvirt_domain.workers :
      [
        for addr in w.network_interface[0].addresses :
        addr if can(regex("^\\d+\\.\\d+\\.\\d+\\.\\d+$", addr))
      ]
    ])

  })

  filename = "${local.local_env_path}/hosts.ini"

  depends_on = [
    null_resource.env_directory,
    null_resource.sleep_before_inventory
  ]
}

###
### Import Kubeconfig
###
resource "null_resource" "kubeconfig" {
  depends_on = [
    null_resource.env_directory,
    libvirt_domain.masters,
    libvirt_domain.workers
  ]

  triggers = {
    path = local.local_env_path
  }

  # Create/fetch kubeconfig
  provisioner "local-exec" {
    command = <<EOT
echo "Fetching kubeconfig into ${self.triggers.path}/kubeconfig"
ssh -o StrictHostKeyChecking=no -i ${self.triggers.path}/.key.private \
${var.cluster.username}@${libvirt_domain.masters[0].network_interface[0].addresses[0]} \
"sudo cat /etc/rancher/k3s/k3s.yaml" | sed "s/127.0.0.1/${libvirt_domain.masters[0].network_interface[0].addresses[0]}/" \
> ${self.triggers.path}/kubeconfig
EOT
  }

  # Cleanup on destroy
  provisioner "local-exec" {
    when    = destroy
    command = "rm -f ${self.triggers.path}/kubeconfig"
  }
}

###
### Output
###

# Output the node IPs
output "cluster_nodes" {
  description = "The IP addresses of the cluster nodes."

  value = {
    masters = flatten([
      for m in libvirt_domain.masters :
      m.network_interface[0].addresses
    ])

    workers = flatten([
      for w in libvirt_domain.workers :
      w.network_interface[0].addresses
    ])
  }
}

output "kubeconfig_command" {
  value = var.cluster.cloud_init_selected == "k3s" ? (<<-EOT
kubecm add -cf env/KVM/${terraform.workspace}/kubeconfig --context-name k3s-${terraform.workspace} --create
# Or :
export KUBECONFIG=env/KVM/${terraform.workspace}/kubeconfig
# Then :
kubectl get nodes
EOT
) : ""
}